// Coordinates and hint data for all game locations.
// City coordinates are approximate (city center). Country data drives
// the progressive hint system.

interface CountryInfo {
  continent: string;
  lat: number;
  lng: number;
  // 3 things the country is known for (cultural, geographic, food, etc.)
  knownFor: [string, string, string];
  // One iconic landmark/monument
  landmark: string;
}

interface LocationGeo {
  lat: number;
  lng: number;
}

// Country-level metadata
export const COUNTRY_DATA: Record<string, CountryInfo> = {
  Japan: {
    continent: "Asia",
    lat: 36.2, lng: 138.25,
    knownFor: ["sushi", "bullet trains", "cherry blossoms"],
    landmark: "Mount Fuji",
  },
  France: {
    continent: "Europe",
    lat: 46.6, lng: 2.2,
    knownFor: ["wine", "the Eiffel Tower", "fashion"],
    landmark: "the Eiffel Tower",
  },
  "United Kingdom": {
    continent: "Europe",
    lat: 55.38, lng: -3.44,
    knownFor: ["fish and chips", "royal palaces", "The Beatles"],
    landmark: "Big Ben",
  },
  Italy: {
    continent: "Europe",
    lat: 41.9, lng: 12.5,
    knownFor: ["pizza", "ancient Roman ruins", "Renaissance art"],
    landmark: "the Colosseum",
  },
  "United States": {
    continent: "North America",
    lat: 39.83, lng: -98.58,
    knownFor: ["hamburgers", "Hollywood", "jazz music"],
    landmark: "the Statue of Liberty",
  },
  Australia: {
    continent: "Oceania",
    lat: -25.27, lng: 133.78,
    knownFor: ["kangaroos", "the Great Barrier Reef", "surfing"],
    landmark: "the Sydney Opera House",
  },
  "United Arab Emirates": {
    continent: "Asia",
    lat: 23.42, lng: 53.85,
    knownFor: ["skyscrapers", "desert safaris", "gold markets"],
    landmark: "the Burj Khalifa",
  },
  China: {
    continent: "Asia",
    lat: 35.86, lng: 104.2,
    knownFor: ["the Great Wall", "Peking duck", "kung fu"],
    landmark: "the Great Wall of China",
  },
  Brazil: {
    continent: "South America",
    lat: -14.24, lng: -51.93,
    knownFor: ["samba", "football", "the Amazon rainforest"],
    landmark: "Christ the Redeemer",
  },
  Egypt: {
    continent: "Africa",
    lat: 26.82, lng: 30.8,
    knownFor: ["pyramids", "pharaohs", "the Nile river"],
    landmark: "the Great Pyramids of Giza",
  },
  Netherlands: {
    continent: "Europe",
    lat: 52.13, lng: 5.29,
    knownFor: ["tulips", "windmills", "cheese markets"],
    landmark: "the canals of Amsterdam",
  },
  Greece: {
    continent: "Europe",
    lat: 39.07, lng: 21.82,
    knownFor: ["olive oil", "ancient mythology", "white-washed villages"],
    landmark: "the Parthenon",
  },
  Peru: {
    continent: "South America",
    lat: -9.19, lng: -75.02,
    knownFor: ["Machu Picchu", "ceviche", "the Andes mountains"],
    landmark: "Machu Picchu",
  },
  Russia: {
    continent: "Europe/Asia",
    lat: 61.52, lng: 105.32,
    knownFor: ["vodka", "matryoshka dolls", "the Trans-Siberian Railway"],
    landmark: "Saint Basil's Cathedral",
  },
  India: {
    continent: "Asia",
    lat: 20.59, lng: 78.96,
    knownFor: ["curry spice", "Bollywood movies", "yoga"],
    landmark: "the Taj Mahal",
  },
  Spain: {
    continent: "Europe",
    lat: 40.46, lng: -3.75,
    knownFor: ["flamenco", "paella", "siestas"],
    landmark: "the Sagrada Familia",
  },
  "South Korea": {
    continent: "Asia",
    lat: 35.91, lng: 127.77,
    knownFor: ["kimchi", "K-pop music", "technology"],
    landmark: "Gyeongbokgung Palace",
  },
  Turkey: {
    continent: "Europe/Asia",
    lat: 38.96, lng: 35.24,
    knownFor: ["Turkish delight", "hot air balloons", "hammams"],
    landmark: "Hagia Sophia",
  },
  Thailand: {
    continent: "Asia",
    lat: 15.87, lng: 100.99,
    knownFor: ["pad thai", "elephant sanctuaries", "floating markets"],
    landmark: "Wat Arun",
  },
  Germany: {
    continent: "Europe",
    lat: 51.17, lng: 10.45,
    knownFor: ["sausages", "Oktoberfest", "autobahn"],
    landmark: "the Brandenburg Gate",
  },
  "Hong Kong": {
    continent: "Asia",
    lat: 22.32, lng: 114.17,
    knownFor: ["dim sum", "skyscrapers", "night markets"],
    landmark: "Victoria Harbour",
  },
  Canada: {
    continent: "North America",
    lat: 56.13, lng: -106.35,
    knownFor: ["maple syrup", "ice hockey", "the Northern Lights"],
    landmark: "the CN Tower",
  },
  "South Africa": {
    continent: "Africa",
    lat: -30.56, lng: 22.94,
    knownFor: ["safaris", "Nelson Mandela", "braai barbecue"],
    landmark: "Table Mountain",
  },
  Morocco: {
    continent: "Africa",
    lat: 31.79, lng: -7.09,
    knownFor: ["couscous", "berber carpets", "spice markets"],
    landmark: "Jemaa el-Fnaa square",
  },
  Kenya: {
    continent: "Africa",
    lat: -0.02, lng: 37.91,
    knownFor: ["the Great Migration", "safaris", "long-distance running"],
    landmark: "the Maasai Mara",
  },
  Ethiopia: {
    continent: "Africa",
    lat: 9.15, lng: 40.49,
    knownFor: ["coffee origin", "rock-hewn churches", "injera bread"],
    landmark: "the Rock-Hewn Churches of Lalibela",
  },
  Tanzania: {
    continent: "Africa",
    lat: -6.37, lng: 34.89,
    knownFor: ["Serengeti plains", "coffee", "Zanzibar beaches"],
    landmark: "Mount Kilimanjaro",
  },
  Senegal: {
    continent: "Africa",
    lat: 14.5, lng: -14.45,
    knownFor: ["mbalax music", "teranga hospitality", "peanut stews"],
    landmark: "the African Renaissance Monument",
  },
  Nigeria: {
    continent: "Africa",
    lat: 9.08, lng: 8.68,
    knownFor: ["Afrobeats music", "Nollywood films", "jollof rice"],
    landmark: "Zuma Rock",
  },
  Namibia: {
    continent: "Africa",
    lat: -22.96, lng: 18.49,
    knownFor: ["sand dunes", "cheetahs", "the Skeleton Coast"],
    landmark: "the red dunes of Sossusvlei",
  },
  Rwanda: {
    continent: "Africa",
    lat: -1.94, lng: 29.87,
    knownFor: ["mountain gorillas", "thousand hills", "clean streets"],
    landmark: "Volcanoes National Park",
  },
  Ghana: {
    continent: "Africa",
    lat: 7.95, lng: -1.02,
    knownFor: ["gold", "kente cloth", "cocoa beans"],
    landmark: "Kwame Nkrumah Mausoleum",
  },
  Madagascar: {
    continent: "Africa",
    lat: -18.77, lng: 46.85,
    knownFor: ["lemurs", "baobab trees", "vanilla"],
    landmark: "the Avenue of the Baobabs",
  },
  Uganda: {
    continent: "Africa",
    lat: 0.32, lng: 32.57,
    knownFor: ["mountain gorillas", "the Nile river source", "banana beer"],
    landmark: "the Rwenzori Mountains",
  },
  "Ivory Coast": {
    continent: "Africa",
    lat: 7.54, lng: -5.55,
    knownFor: ["cocoa", "attieke cassava", "zouglou music"],
    landmark: "the Basilica of Our Lady of Peace",
  },
  Zambia: {
    continent: "Africa",
    lat: -13.13, lng: 27.85,
    knownFor: ["Victoria Falls", "safaris", "emeralds"],
    landmark: "Victoria Falls",
  },
  Botswana: {
    continent: "Africa",
    lat: -22.33, lng: 24.68,
    knownFor: ["the Okavango Delta", "meerkats", "diamonds"],
    landmark: "the Okavango Delta",
  },
  Taiwan: {
    continent: "Asia",
    lat: 23.7, lng: 120.96,
    knownFor: ["bubble tea", "night markets", "semi-conductors"],
    landmark: "Taipei 101",
  },
  Vietnam: {
    continent: "Asia",
    lat: 16.0, lng: 108.0,
    knownFor: ["pho noodle soup", "ha long bay", "motorcycles"],
    landmark: "Ha Long Bay",
  },
  Philippines: {
    continent: "Asia",
    lat: 12.88, lng: 121.77,
    knownFor: ["rice terraces", "jeepneys", "tropical beaches"],
    landmark: "the Banaue Rice Terraces",
  },
  Cambodia: {
    continent: "Asia",
    lat: 12.57, lng: 104.99,
    knownFor: ["Angkor Wat", "amok curry", "rice paddies"],
    landmark: "Angkor Wat",
  },
  Myanmar: {
    continent: "Asia",
    lat: 21.91, lng: 95.96,
    knownFor: ["golden pagodas", "tea leaf salad", "thanaka paste"],
    landmark: "the temples of Bagan",
  },
  Malaysia: {
    continent: "Asia",
    lat: 4.21, lng: 101.98,
    knownFor: ["nasi lemak", "Petronas Towers", "rainforests"],
    landmark: "the Petronas Towers",
  },
  Singapore: {
    continent: "Asia",
    lat: 1.35, lng: 103.82,
    knownFor: ["chilli crab", "hawker centers", "Gardens by the Bay"],
    landmark: "Marina Bay Sands",
  },
  Indonesia: {
    continent: "Asia",
    lat: -0.79, lng: 113.92,
    knownFor: ["batik fabric", "nasi goreng", "komodo dragons"],
    landmark: "Borobudur Temple",
  },
  Laos: {
    continent: "Asia",
    lat: 19.86, lng: 102.5,
    knownFor: ["sticky rice", "Tuk Tuk taxis", "Kuong Si falls"],
    landmark: "Kuang Si Falls",
  },
  Mongolia: {
    continent: "Asia",
    lat: 46.86, lng: 103.85,
    knownFor: ["yurts", "throat singing", "the Gobi Desert"],
    landmark: "the Gobi Desert",
  },
  "Sri Lanka": {
    continent: "Asia",
    lat: 7.87, lng: 80.77,
    knownFor: ["cinnamon", "tea plantations", "elephant safaris"],
    landmark: "Sigiriya Rock Fortress",
  },
  Nepal: {
    continent: "Asia",
    lat: 28.39, lng: 84.12,
    knownFor: ["Mount Everest", "momo dumplings", "Buddhist monasteries"],
    landmark: "Mount Everest",
  },
  Bhutan: {
    continent: "Asia",
    lat: 27.51, lng: 90.44,
    knownFor: ["Gross National Happiness", "monasteries", "archery"],
    landmark: "Paro Taktsang (Tiger's Nest)",
  },
  Bangladesh: {
    continent: "Asia",
    lat: 23.68, lng: 90.36,
    knownFor: ["rice fields", "rickshaws", "Sundarbans mangroves"],
    landmark: "the Sundarbans mangrove forest",
  },
  Pakistan: {
    continent: "Asia",
    lat: 30.37, lng: 69.35,
    knownFor: ["biryani", "the Indus Valley", "mountain peaks"],
    landmark: "Badshahi Mosque",
  },
  Israel: {
    continent: "Asia",
    lat: 31.05, lng: 34.85,
    knownFor: ["hummus", "the Dead Sea", "religious sites"],
    landmark: "the Dome of the Rock",
  },
  "Saudi Arabia": {
    continent: "Asia",
    lat: 23.89, lng: 45.08,
    knownFor: ["oil", "Arabian coffee", "the Red Sea coast"],
    landmark: "Al-Masjid an-Nabawi",
  },
  Qatar: {
    continent: "Asia",
    lat: 25.35, lng: 51.18,
    knownFor: ["pearl diving", "desert dunes", "World Cup stadiums"],
    landmark: "the Museum of Islamic Art",
  },
  Oman: {
    continent: "Asia",
    lat: 21.47, lng: 55.97,
    knownFor: ["frankincense", "wadis", "dhow boats"],
    landmark: "the Sultan Qaboos Grand Mosque",
  },
  Jordan: {
    continent: "Asia",
    lat: 30.59, lng: 36.24,
    knownFor: ["Petra", "dead sea", "mosaic art"],
    landmark: "Petra",
  },
  Lebanon: {
    continent: "Asia",
    lat: 33.85, lng: 35.86,
    knownFor: ["tabbouleh", "cedar trees", "Roman ruins"],
    landmark: "the Pigeon Rocks",
  },
  Kuwait: {
    continent: "Asia",
    lat: 29.31, lng: 47.48,
    knownFor: ["oil", "Arabian hospitality", "dhow building"],
    landmark: "the Kuwait Towers",
  },
  Bahrain: {
    continent: "Asia",
    lat: 26.07, lng: 50.56,
    knownFor: ["pearl diving", "Formula 1", "date palms"],
    landmark: "the Bahrain World Trade Center",
  },
  Armenia: {
    continent: "Asia",
    lat: 40.07, lng: 45.04,
    knownFor: ["apricots", "ancient monasteries", "brandy"],
    landmark: "the Cascade Complex",
  },
  Georgia: {
    continent: "Asia",
    lat: 42.32, lng: 43.36,
    knownFor: ["wine origin", "khachapuri bread", "Caucasus mountains"],
    landmark: "Narikala Fortress",
  },
  Uzbekistan: {
    continent: "Asia",
    lat: 41.38, lng: 64.59,
    knownFor: ["Silk Road cities", "plov rice", "blue tile mosques"],
    landmark: "Registan Square",
  },
  Kazakhstan: {
    continent: "Asia",
    lat: 48.02, lng: 66.92,
    knownFor: ["steppes", "horse riding", "Baiterek Tower"],
    landmark: "the Charyn Canyon",
  },
  Portugal: {
    continent: "Europe",
    lat: 39.4, lng: -8.22,
    knownFor: ["pastel de nata", "port wine", "blue tile art"],
    landmark: "Belém Tower",
  },
  Ireland: {
    continent: "Europe",
    lat: 53.14, lng: -7.69,
    knownFor: ["Guinness beer", "green landscapes", "St. Patrick's Day"],
    landmark: "the Cliffs of Moher",
  },
  Scotland: {
    continent: "Europe",
    lat: 56.49, lng: -4.2,
    knownFor: ["whisky", "bagpipes", "loch ness"],
    landmark: "Edinburgh Castle",
  },
  Switzerland: {
    continent: "Europe",
    lat: 46.82, lng: 8.23,
    knownFor: ["chocolate", "Swiss cheese", "the Alps"],
    landmark: "the Matterhorn",
  },
  Austria: {
    continent: "Europe",
    lat: 47.52, lng: 14.55,
    knownFor: ["classical music", "schnitzel", "the Alps"],
    landmark: "Schönbrunn Palace",
  },
  "Czech Republic": {
    continent: "Europe",
    lat: 49.82, lng: 15.47,
    knownFor: ["beer culture", "puppets", "Bohemian crystal"],
    landmark: "Charles Bridge",
  },
  Poland: {
    continent: "Europe",
    lat: 51.92, lng: 19.15,
    knownFor: ["pierogi dumplings", "amber jewelry", "Wieliczka salt mine"],
    landmark: "Wawel Castle",
  },
  Hungary: {
    continent: "Europe",
    lat: 47.16, lng: 19.5,
    knownFor: ["paprika", "thermal baths", "goulash"],
    landmark: "the Parliament Building",
  },
  Croatia: {
    continent: "Europe",
    lat: 44.45, lng: 16.51,
    knownFor: ["Dubrovnik", "Plitvice Lakes", "truffles"],
    landmark: "the Old Town Walls of Dubrovnik",
  },
  Sweden: {
    continent: "Europe",
    lat: 60.13, lng: 18.64,
    knownFor: ["meatballs", "IKEA", "ABBA"],
    landmark: "Gamla Stan old town",
  },
  Norway: {
    continent: "Europe",
    lat: 60.47, lng: 8.47,
    knownFor: ["fjords", "salmon", "the Northern Lights"],
    landmark: "the Geirangerfjord",
  },
  Denmark: {
    continent: "Europe",
    lat: 56.26, lng: 9.5,
    knownFor: ["Lego", "pastry", "bicycle culture"],
    landmark: "the Little Mermaid statue",
  },
  Finland: {
    continent: "Europe",
    lat: 61.92, lng: 25.75,
    knownFor: ["saunas", "Northern Lights", "reindeer"],
    landmark: "Suomenlinna Fortress",
  },
  Belgium: {
    continent: "Europe",
    lat: 50.5, lng: 4.47,
    knownFor: ["chocolate", "waffles", "fries"],
    landmark: "the Grand Place",
  },
  Ukraine: {
    continent: "Europe",
    lat: 48.38, lng: 31.17,
    knownFor: ["borscht soup", "sunflower fields", "St. Sophia's"],
    landmark: "Saint Sophia Cathedral",
  },
  Romania: {
    continent: "Europe",
    lat: 45.94, lng: 24.97,
    knownFor: ["Dracula legend", "painted monasteries", "sarmale rolls"],
    landmark: "the Palace of the Parliament",
  },
  Bulgaria: {
    continent: "Europe",
    lat: 42.73, lng: 25.49,
    knownFor: ["yogurt", "rose oil", "Black Sea resorts"],
    landmark: "the Alexander Nevsky Cathedral",
  },
  Serbia: {
    continent: "Europe",
    lat: 44.02, lng: 20.46,
    knownFor: ["rakiya brandy", "slava festivals", "Nikola Tesla"],
    landmark: "Kalemegdan Fortress",
  },
  Slovenia: {
    continent: "Europe",
    lat: 46.15, lng: 14.99,
    knownFor: ["Lake Bled", "caves", "wine"],
    landmark: "Ljubljana Castle",
  },
  Slovakia: {
    continent: "Europe",
    lat: 48.67, lng: 19.7,
    knownFor: ["Tatra mountains", "medieval castles", "Bryndza cheese"],
    landmark: "Bratislava Castle",
  },
  Lithuania: {
    continent: "Europe",
    lat: 55.17, lng: 23.88,
    knownFor: ["amber", "basketball", "Gediminas Tower"],
    landmark: "Gediminas Tower",
  },
  Latvia: {
    continent: "Europe",
    lat: 56.88, lng: 24.6,
    knownFor: ["Art Nouveau architecture", "baltic beaches", "Ligo festival"],
    landmark: "the House of the Black Heads",
  },
  Estonia: {
    continent: "Europe",
    lat: 58.6, lng: 25.01,
    knownFor: ["digital society", "medieval Tallinn", "e-residency"],
    landmark: "Toompea Castle",
  },
  Iceland: {
    continent: "Europe",
    lat: 64.96, lng: -19.02,
    knownFor: ["geysers", "volcanoes", "hot springs"],
    landmark: "Hallgrímskirkja Church",
  },
  Malta: {
    continent: "Europe",
    lat: 35.94, lng: 14.38,
    knownFor: ["temples", "blue lagoon", "pastizzi pastries"],
    landmark: "St. John's Co-Cathedral",
  },
  Monaco: {
    continent: "Europe",
    lat: 43.73, lng: 7.42,
    knownFor: ["Formula 1 Grand Prix", "casinos", "luxury yachts"],
    landmark: "the Casino de Monte-Carlo",
  },
  Cyprus: {
    continent: "Europe",
    lat: 35.13, lng: 33.43,
    knownFor: ["halloumi cheese", "beaches", "ancient ruins"],
    landmark: "the Tombs of the Kings",
  },
  Mexico: {
    continent: "North America",
    lat: 23.63, lng: -102.55,
    knownFor: ["tacos", "mariachi music", "Day of the Dead"],
    landmark: "Chichen Itza",
  },
  "Costa Rica": {
    continent: "North America",
    lat: 9.75, lng: -83.75,
    knownFor: ["rainforests", "sloths", "volcanoes"],
    landmark: "Arenal Volcano",
  },
  Panama: {
    continent: "North America",
    lat: 8.54, lng: -80.78,
    knownFor: ["the Panama Canal", "coffee", "San Blas islands"],
    landmark: "the Panama Canal",
  },
  Cuba: {
    continent: "North America",
    lat: 21.52, lng: -77.78,
    knownFor: ["cigars", "old cars", "salsa music"],
    landmark: "El Capitolio",
  },
  "Puerto Rico": {
    continent: "North America",
    lat: 18.22, lng: -66.59,
    knownFor: ["mofongo", "beaches", "biobays"],
    landmark: "El Morro fortress",
  },
  "Dominican Republic": {
    continent: "North America",
    lat: 18.74, lng: -70.16,
    knownFor: ["merengue music", "mangú", "coconut beaches"],
    landmark: "the Alcázar de Colón",
  },
  Guatemala: {
    continent: "North America",
    lat: 15.78, lng: -90.23,
    knownFor: ["Mayan ruins", "volcanoes", "textiles"],
    landmark: "Tikal",
  },
  Honduras: {
    continent: "North America",
    lat: 15.2, lng: -86.24,
    knownFor: ["Copán ruins", "coral reefs", "bananas"],
    landmark: "the Copán Ruins",
  },
  Jamaica: {
    continent: "North America",
    lat: 18.11, lng: -77.3,
    knownFor: ["reggae music", "Blue Mountain coffee", "jerk chicken"],
    landmark: "Devon House",
  },
  Colombia: {
    continent: "South America",
    lat: 4.57, lng: -74.3,
    knownFor: ["coffee", "emeralds", "cumbia music"],
    landmark: "the Gold Museum",
  },
  Argentina: {
    continent: "South America",
    lat: -38.42, lng: -63.62,
    knownFor: ["tango", "steak", "Maradona"],
    landmark: "the Obelisco",
  },
  Chile: {
    continent: "South America",
    lat: -35.68, lng: -71.54,
    knownFor: ["Easter Island", "wine", "Patagonia"],
    landmark: "the Moai Statues",
  },
  Ecuador: {
    continent: "South America",
    lat: -1.83, lng: -78.18,
    knownFor: ["the Galapagos", "bananas", "the equator line"],
    landmark: "the Mitad del Mundo",
  },
  Venezuela: {
    continent: "South America",
    lat: 6.42, lng: -66.59,
    knownFor: ["Angel Falls", "arepas", "oil reserves"],
    landmark: "Angel Falls",
  },
  Bolivia: {
    continent: "South America",
    lat: -16.29, lng: -63.59,
    knownFor: ["salt flats", "llamas", "indigenous culture"],
    landmark: "the Uyuni Salt Flats",
  },
  Paraguay: {
    continent: "South America",
    lat: -23.44, lng: -58.44,
    knownFor: ["yerba mate", "Itaipu Dam", "lacework"],
    landmark: "the Itaipu Dam",
  },
  Uruguay: {
    continent: "South America",
    lat: -32.52, lng: -55.77,
    knownFor: ["mate tea", "beef", "Uruguayan football"],
    landmark: "Plaza Independencia",
  },
  Guyana: {
    continent: "South America",
    lat: 4.86, lng: -58.93,
    knownFor: ["Kaieteur Falls", "rainforest", "rum"],
    landmark: "Kaieteur Falls",
  },
  "New Zealand": {
    continent: "Oceania",
    lat: -40.9, lng: 174.89,
    knownFor: ["rugby", "hobbiton", "kiwi fruit"],
    landmark: "Milford Sound",
  },
  Fiji: {
    continent: "Oceania",
    lat: -17.71, lng: 177.92,
    knownFor: ["coral reefs", "kava drink", "friendly people"],
    landmark: "the Sri Siva Subramaniya Temple",
  },
  "Papua New Guinea": {
    continent: "Oceania",
    lat: -6.31, lng: 143.96,
    knownFor: ["tribal cultures", "coral reefs", "birds of paradise"],
    landmark: "the Kokoda Track",
  },
  Samoa: {
    continent: "Oceania",
    lat: -13.76, lng: -172.1,
    knownFor: ["tattoo origin", "coconut", "fa'a Samoa culture"],
    landmark: "Robert Louis Stevenson Museum",
  },
  Vanuatu: {
    continent: "Oceania",
    lat: -15.38, lng: 166.96,
    knownFor: ["volcanoes", "custom villages", "blue holes"],
    landmark: "Mount Yasur Volcano",
  },
  Algeria: {
    continent: "Africa",
    lat: 28.03, lng: 1.66,
    knownFor: ["Sahara desert", "couscous", "Roman ruins"],
    landmark: "the Casbah of Algiers",
  },
  Tunisia: {
    continent: "Africa",
    lat: 33.89, lng: 9.54,
    knownFor: ["olive oil", "Star Wars film sets", "Roman amphitheaters"],
    landmark: "the Medina of Tunis",
  },
  Libya: {
    continent: "Africa",
    lat: 26.34, lng: 17.23,
    knownFor: ["Leptis Magna ruins", "desert", "olive oil"],
    landmark: "the Severan Arch at Leptis Magna",
  },
  Sudan: {
    continent: "Africa",
    lat: 12.86, lng: 30.22,
    knownFor: ["Nubian pyramids", "the Nile", "gold mines"],
    landmark: "the Pyramids of Meroe",
  },
  Zimbabwe: {
    continent: "Africa",
    lat: -19.02, lng: 29.15,
    knownFor: ["Great Zimbabwe ruins", "Victoria Falls", "wildlife"],
    landmark: "Great Zimbabwe",
  },
  Mozambique: {
    continent: "Africa",
    lat: -18.67, lng: 35.53,
    knownFor: ["piri-piri chicken", "beaches", "dhow sailing"],
    landmark: "Maputo Railway Station",
  },
  Angola: {
    continent: "Africa",
    lat: -11.2, lng: 17.87,
    knownFor: ["diamonds", "oil", "Kalandula Falls"],
    landmark: "the Fortress of São Miguel",
  },
  "DR Congo": {
    continent: "Africa",
    lat: -4.04, lng: 21.76,
    knownFor: ["the Congo river", "bonobos", "copper mining"],
    landmark: "Virunga National Park",
  },
};

// City-level coordinates for precise pin placement.
// Keys are "country:city".
const CITY_COORDS: Record<string, LocationGeo> = {
  "Japan:Tokyo": { lat: 35.6762, lng: 139.6503 },
  "Japan:Kyoto": { lat: 35.0116, lng: 135.7681 },
  "Japan:Hiroshima": { lat: 34.3853, lng: 132.4553 },
  "France:Paris": { lat: 48.8566, lng: 2.3522 },
  "France:Marseille": { lat: 43.2965, lng: 5.3698 },
  "France:Lyon": { lat: 45.7640, lng: 4.8357 },
  "United Kingdom:London": { lat: 51.5074, lng: -0.1278 },
  "Italy:Rome": { lat: 41.9028, lng: 12.4964 },
  "Italy:Venice": { lat: 45.4408, lng: 12.3155 },
  "Italy:Florence": { lat: 43.7696, lng: 11.2558 },
  "Italy:Milan": { lat: 45.4642, lng: 9.1900 },
  "Italy:Pisa": { lat: 43.7229, lng: 10.4017 },
  "United States:New York City": { lat: 40.7128, lng: -74.006 },
  "United States:San Francisco": { lat: 37.7749, lng: -122.4194 },
  "United States:Chicago": { lat: 41.8781, lng: -87.6298 },
  "United States:Washington D.C.": { lat: 38.9072, lng: -77.0369 },
  "United States:Seattle": { lat: 47.6062, lng: -122.3321 },
  "United States:New Orleans": { lat: 29.9511, lng: -90.0715 },
  "United States:Las Vegas": { lat: 36.1699, lng: -115.1398 },
  "United States:Grand Canyon": { lat: 36.1069, lng: -112.1129 },
  "United States:Miami": { lat: 25.7617, lng: -80.1918 },
  "United States:Portland": { lat: 45.5152, lng: -122.6784 },
  "United States:Nashville": { lat: 36.1627, lng: -86.7816 },
  "United States:Savannah": { lat: 32.0809, lng: -81.0912 },
  "United States:Denver": { lat: 39.7392, lng: -104.9903 },
  "United States:Boston": { lat: 42.3601, lng: -71.0589 },
  "United States:Yellowstone": { lat: 44.4280, lng: -110.5885 },
  "United States:Philadelphia": { lat: 39.9526, lng: -75.1652 },
  "Australia:Sydney": { lat: -33.8688, lng: 151.2093 },
  "Australia:Melbourne": { lat: -37.8136, lng: 144.9631 },
  "Australia:Great Barrier Reef": { lat: -18.2871, lng: 147.6992 },
  "Australia:Perth": { lat: -31.9505, lng: 115.8605 },
  "Australia:Hobart": { lat: -42.8821, lng: 147.3272 },
  "Australia:Uluru": { lat: -25.3444, lng: 131.0369 },
  "Australia:Gold Coast": { lat: -28.0167, lng: 153.4000 },
  "United Arab Emirates:Dubai": { lat: 25.2048, lng: 55.2708 },
  "China:Beijing": { lat: 39.9042, lng: 116.4074 },
  "China:Shanghai": { lat: 31.2304, lng: 121.4737 },
  "China:Guilin": { lat: 25.2736, lng: 110.2900 },
  "China:Xi'an": { lat: 34.3416, lng: 108.9398 },
  "Brazil:Rio de Janeiro": { lat: -22.9068, lng: -43.1729 },
  "Brazil:Salvador": { lat: -12.9714, lng: -38.5014 },
  "Brazil:Brasília": { lat: -15.7975, lng: -47.8919 },
  "Egypt:Cairo": { lat: 30.0444, lng: 31.2357 },
  "Netherlands:Amsterdam": { lat: 52.3676, lng: 4.9041 },
  "Netherlands:Rotterdam": { lat: 51.9244, lng: 4.4777 },
  "Greece:Santorini": { lat: 36.3932, lng: 25.4615 },
  "Greece:Athens": { lat: 37.9838, lng: 23.7275 },
  "Peru:Cusco": { lat: -13.5320, lng: -71.9675 },
  "Peru:Lima": { lat: -12.0464, lng: -77.0428 },
  "Russia:Moscow": { lat: 55.7558, lng: 37.6173 },
  "India:Mumbai": { lat: 19.0760, lng: 72.8777 },
  "India:Jaipur": { lat: 26.9124, lng: 75.7873 },
  "India:Agra": { lat: 27.1767, lng: 78.0081 },
  "India:Varanasi": { lat: 25.3176, lng: 82.9739 },
  "India:Amritsar": { lat: 31.6340, lng: 74.8723 },
  "Spain:Barcelona": { lat: 41.3874, lng: 2.1686 },
  "Spain:Granada": { lat: 37.1773, lng: -3.5986 },
  "Spain:Seville": { lat: 37.3891, lng: -5.9845 },
  "South Korea:Seoul": { lat: 37.5665, lng: 126.978 },
  "South Korea:Busan": { lat: 35.1796, lng: 129.0756 },
  "Turkey:Istanbul": { lat: 41.0082, lng: 28.9784 },
  "Turkey:Cappadocia": { lat: 38.6383, lng: 34.8298 },
  "Turkey:Pamukkale": { lat: 37.9259, lng: 29.1239 },
  "Thailand:Bangkok": { lat: 13.7563, lng: 100.5018 },
  "Germany:Berlin": { lat: 52.5200, lng: 13.4050 },
  "Germany:Munich": { lat: 48.1351, lng: 11.5820 },
  "Germany:Cologne": { lat: 50.9375, lng: 6.9603 },
  "Hong Kong:Hong Kong": { lat: 22.3193, lng: 114.1694 },
  "Canada:Toronto": { lat: 43.6532, lng: -79.3832 },
  "Canada:Vancouver": { lat: 49.2827, lng: -123.1207 },
  "Canada:Montreal": { lat: 45.5017, lng: -73.5673 },
  "Canada:Quebec City": { lat: 46.8139, lng: -71.208 },
  "Canada:Calgary": { lat: 51.0447, lng: -114.0719 },
  "Canada:Halifax": { lat: 44.6488, lng: -63.5752 },
  "South Africa:Cape Town": { lat: -33.9249, lng: 18.4241 },
  "South Africa:Johannesburg": { lat: -26.2041, lng: 28.0473 },
  "Morocco:Marrakech": { lat: 31.6295, lng: -7.9811 },
  "Kenya:Nairobi": { lat: -1.2921, lng: 36.8219 },
  "Ethiopia:Lalibela": { lat: 12.0330, lng: 39.0480 },
  "Tanzania:Arusha": { lat: -3.3869, lng: 36.6830 },
  "Senegal:Dakar": { lat: 14.7167, lng: -17.4677 },
  "Nigeria:Lagos": { lat: 6.5244, lng: 3.3792 },
  "Namibia:Windhoek": { lat: -22.5609, lng: 17.0658 },
  "Rwanda:Kigali": { lat: -1.9441, lng: 30.0619 },
  "Ghana:Accra": { lat: 5.6037, lng: -0.1870 },
  "Madagascar:Antananarivo": { lat: -18.8792, lng: 47.5079 },
  "Uganda:Kampala": { lat: 0.3476, lng: 32.5825 },
  "Ivory Coast:Yamoussoukro": { lat: 6.8205, lng: -5.2767 },
  "Zambia:Livingstone": { lat: -17.8597, lng: 25.8705 },
  "Botswana:Maun": { lat: -19.9977, lng: 23.4186 },
  "Taiwan:Taipei": { lat: 25.0330, lng: 121.5654 },
  "Vietnam:Hanoi": { lat: 21.0278, lng: 105.8342 },
  "Philippines:Manila": { lat: 14.5995, lng: 120.9842 },
  "Cambodia:Siem Reap": { lat: 13.3633, lng: 103.8564 },
  "Myanmar:Bagan": { lat: 21.1717, lng: 94.8584 },
  "Malaysia:Kuala Lumpur": { lat: 3.1390, lng: 101.6869 },
  "Singapore:Singapore": { lat: 1.3521, lng: 103.8198 },
  "Indonesia:Bali": { lat: -8.3405, lng: 115.0920 },
  "Laos:Luang Prabang": { lat: 19.8833, lng: 102.1333 },
  "Mongolia:Ulaanbaatar": { lat: 47.8864, lng: 106.9057 },
  "Sri Lanka:Kandy": { lat: 7.2906, lng: 80.6337 },
  "Nepal:Kathmandu": { lat: 27.7172, lng: 85.3240 },
  "Bhutan:Paro": { lat: 27.4411, lng: 89.4161 },
  "Bangladesh:Dhaka": { lat: 23.7104, lng: 90.4074 },
  "Pakistan:Lahore": { lat: 31.5497, lng: 74.3436 },
  "Israel:Jerusalem": { lat: 31.7683, lng: 35.2137 },
  "Saudi Arabia:Riyadh": { lat: 24.7136, lng: 46.6753 },
  "Qatar:Doha": { lat: 25.2854, lng: 51.5310 },
  "Oman:Muscat": { lat: 23.5880, lng: 58.3829 },
  "Jordan:Petra": { lat: 30.3285, lng: 35.4444 },
  "Lebanon:Beirut": { lat: 33.8938, lng: 35.5018 },
  "Kuwait:Kuwait City": { lat: 29.3759, lng: 47.9774 },
  "Bahrain:Manama": { lat: 26.2285, lng: 50.5860 },
  "Armenia:Yerevan": { lat: 40.1792, lng: 44.4991 },
  "Georgia:Tbilisi": { lat: 41.7151, lng: 44.8271 },
  "Uzbekistan:Samarkand": { lat: 39.6543, lng: 66.9597 },
  "Kazakhstan:Almaty": { lat: 43.2389, lng: 76.8897 },
  "Portugal:Lisbon": { lat: 38.7223, lng: -9.1393 },
  "Ireland:Dublin": { lat: 53.3498, lng: -6.2603 },
  "Scotland:Edinburgh": { lat: 55.9533, lng: -3.1883 },
  "Switzerland:Zermatt": { lat: 46.0207, lng: 7.7491 },
  "Austria:Vienna": { lat: 48.2082, lng: 16.3738 },
  "Czech Republic:Prague": { lat: 50.0755, lng: 14.4378 },
  "Poland:Kraków": { lat: 50.0647, lng: 19.9450 },
  "Hungary:Budapest": { lat: 47.4979, lng: 19.0402 },
  "Croatia:Dubrovnik": { lat: 42.6507, lng: 18.0944 },
  "Sweden:Stockholm": { lat: 59.3293, lng: 18.0686 },
  "Norway:Bergen": { lat: 60.3913, lng: 5.3221 },
  "Denmark:Copenhagen": { lat: 55.6761, lng: 12.5683 },
  "Finland:Helsinki": { lat: 60.1699, lng: 24.9384 },
  "Belgium:Bruges": { lat: 51.2093, lng: 3.2247 },
  "Ukraine:Kyiv": { lat: 50.4501, lng: 30.5234 },
  "Romania:Bucharest": { lat: 44.4268, lng: 26.1025 },
  "Bulgaria:Sofia": { lat: 42.6977, lng: 23.3219 },
  "Serbia:Belgrade": { lat: 44.7866, lng: 20.4489 },
  "Slovenia:Ljubljana": { lat: 46.0569, lng: 14.5058 },
  "Slovakia:Bratislava": { lat: 48.1486, lng: 17.1077 },
  "Lithuania:Vilnius": { lat: 54.6872, lng: 25.2797 },
  "Latvia:Riga": { lat: 56.9496, lng: 24.1052 },
  "Estonia:Tallinn": { lat: 59.4370, lng: 24.7536 },
  "Iceland:Reykjavik": { lat: 64.1466, lng: -21.9426 },
  "Malta:Valletta": { lat: 35.8997, lng: 14.5147 },
  "Monaco:Monte Carlo": { lat: 43.7402, lng: 7.4266 },
  "Cyprus:Paphos": { lat: 34.7754, lng: 32.4218 },
  "Mexico:Mexico City": { lat: 19.4326, lng: -99.1332 },
  "Costa Rica:San José": { lat: 9.9281, lng: -84.0907 },
  "Panama:Panama City": { lat: 8.9824, lng: -79.5199 },
  "Cuba:Havana": { lat: 23.1136, lng: -82.3666 },
  "Puerto Rico:San Juan": { lat: 18.4655, lng: -66.1057 },
  "Dominican Republic:Santo Domingo": { lat: 18.4861, lng: -69.9312 },
  "Guatemala:Antigua": { lat: 14.5619, lng: -90.7340 },
  "Honduras:Copán": { lat: 14.8387, lng: -89.1457 },
  "Jamaica:Kingston": { lat: 17.9712, lng: -76.7927 },
  "Colombia:Bogotá": { lat: 4.7110, lng: -74.0721 },
  "Argentina:Buenos Aires": { lat: -34.6037, lng: -58.3816 },
  "Argentina:Ushuaia": { lat: -54.8019, lng: -68.3030 },
  "Chile:Santiago": { lat: -33.4489, lng: -70.6693 },
  "Chile:Easter Island": { lat: -27.1127, lng: -109.3497 },
  "Ecuador:Quito": { lat: -0.2299, lng: -78.5249 },
  "Venezuela:Caracas": { lat: 10.4806, lng: -66.9036 },
  "Bolivia:La Paz": { lat: -16.5000, lng: -68.1500 },
  "Paraguay:Asunción": { lat: -25.2637, lng: -57.5759 },
  "Uruguay:Montevideo": { lat: -34.9011, lng: -56.1645 },
  "Guyana:Georgetown": { lat: 6.8045, lng: -58.1548 },
  "New Zealand:Queenstown": { lat: -45.0312, lng: 168.6626 },
  "New Zealand:Rotorua": { lat: -38.1369, lng: 176.2497 },
  "New Zealand:Auckland": { lat: -36.8485, lng: 174.7633 },
  "New Zealand:Wellington": { lat: -41.2865, lng: 174.7762 },
  "New Zealand:Christchurch": { lat: -43.5320, lng: 172.6306 },
  "Fiji:Nadi": { lat: -17.7765, lng: 177.4350 },
  "Papua New Guinea:Port Moresby": { lat: -9.4780, lng: 147.1496 },
  "Samoa:Apia": { lat: -13.8340, lng: -171.7683 },
  "Vanuatu:Port Vila": { lat: -17.7333, lng: 168.3273 },
  "Algeria:Algiers": { lat: 36.7372, lng: 3.0864 },
  "Tunisia:Tunis": { lat: 36.8065, lng: 10.1815 },
  "Libya:Leptis Magna": { lat: 32.6385, lng: 14.2982 },
  "Sudan:Meroe": { lat: 16.9375, lng: 33.7508 },
  "Zimbabwe:Masvingo": { lat: -20.0797, lng: 30.8389 },
  "Mozambique:Maputo": { lat: -25.9692, lng: 32.5732 },
  "Angola:Luanda": { lat: -8.8390, lng: 13.2894 },
  "DR Congo:Kinshasa": { lat: -4.4419, lng: 15.2663 },
  "Scotland:Scotland": { lat: 56.4907, lng: -4.2026 },
  "Japan:Mount Fuji": { lat: 35.3606, lng: 138.7274 },
  "United States:New York": { lat: 40.7128, lng: -74.006 },
};

// Generate 4 progressive hints for a given country
export function generateHints(country: string): string[] {
  const data = COUNTRY_DATA[country];
  if (!data) {
    return [
      "This country has a rich history.",
      "It's famous for its cultural heritage.",
      "Tourists love visiting this destination.",
      `Starts with "${country[0]}"`,
    ];
  }

  return [
    `This country is in ${data.continent}.`,
    `Known for ${data.knownFor[0]} and ${data.knownFor[1]}.`,
    `Home to ${data.landmark}.`,
    `Starts with "${country[0]}".`,
  ];
}

// Get coordinates for a location (city-level or country-level fallback)
export function getLocationCoords(country: string, city: string): LocationGeo {
  // Normalize city name for lookup
  const normalizedCity = city
    .replace(/[éèêë]/g, 'e').replace(/[àâä]/g, 'a')
    .replace(/[ùûü]/g, 'u').replace(/[ôö]/g, 'o')
    .replace(/[îï]/g, 'i').replace(/[ç]/g, 'c');

  const key = `${country}:${city}`;
  const altKey = `${country}:${normalizedCity}`;

  const cityCoord = CITY_COORDS[key] ?? CITY_COORDS[altKey];
  if (cityCoord) return cityCoord;

  // Fallback to country center
  const countryData = COUNTRY_DATA[country];
  if (countryData) return { lat: countryData.lat, lng: countryData.lng };

  // Last resort — center of the Atlantic
  return { lat: 0, lng: 0 };
}
